services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eire
    volumes:
      - /home/kaalu/volumes/sonarr/data:/config
      - /home/kaalu/downloads/tv:/tv #optional
      - /home/kaalu/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true