services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eire
    volumes:
      - /home/kaalu/volumes/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true