services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - CLOUDFLARE_EMAIL=${CF_EMAIL}
      - CLOUDFLARE_API_TOKEN=${CF_API_TOKEN}
      - ACME_AGREE=true
    ports:
      - 2019:2019 # remove if you do not want admin API
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /home/kaalu/volumes/caddy/site:/srv
      - /home/kaalu/volumes/caddy/data:/data
      - /home/kaalu/volumes/caddy/config:/config
    networks:
      - homelab

# create this first before running the docker-compose - docker network create caddy
networks:
  homelab:
    external: true

volumes:
  data:
  config:
