services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eire
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/kaalu/volumes/plex:/config
      - /home/kaalu/downloads/tv:/tv
      - /home/kaalu/downloads/movie:/movies
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true