services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    networks:
      - homelab
    ports:
      - '8100:3001'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network,gpu'
      DASHDOT_CPU_LABEL_LIST: 'brand,model,cores,threads,frequency'
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_STORAGE_LABEL_LIST: 'brand,size,type'
      DASHDOT_NETWORK_LABEL_LIST: 'type,speed_up,speed_down,interface_speed'
      DASHDOT_ACCEPT_OOKLA_EULA: true
      DASHDOT_SHOW_DASH_VERSION: 'icon_hover'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true

networks:
  homelab:
    external: true