services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Eire
    ports:
      - 5055:5055
    volumes:
      - /home/kaalu/volumes/overseerr/config:/app/config
      - /home/kaalu/downloads:/media
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true