services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eire
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/kaalu/volumes/qbittorrent/appdata:/config
      - /home/kaalu/downloads/torrent:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true