services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Eire
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - homelab
    labels:
      glance.name: Flaresolverr
      glance.icon: di:flaresolverr
      glance.url: http://192.168.1.100:8191
      glance.description: Captcha Solver
      glance.id: flaresolverr

networks:
  homelab:
    external: true