services:
  obsidian-couchdb:
    container_name: obsidian-livesync #shortened name
    image: couchdb:3.3.3
    environment:
      - PUID=1000
      - PGID=1000
      # - UMASK=0022
      - TZ=Eire
      - COUCHDB_USER=obsidian_kaalu # optionally change me
      - COUCHDB_PASSWORD=password # definitly change me
    volumes:
      - /home/kaalu/volumes/obsidian/data:/opt/couchdb/data
      # - /mnt/user/appdata/couchdb-obsidian-livesync/etc/local.d:/opt/couchdb/etc/local.d
    ports:
      - "5984:5984"
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://localhost:5984/_up | grep -Eo '\"status\":\"ok\"' || exit 1
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 3
    # depends_on:
    #   obsidian-couchdb:
    #     condition: service_healthy
volumes:
  data: