services:
  requestrr:
    image: thomst08/requestrr
    hostname: requestrr
    container_name: requestrr
    ports:
    - 4545:4545
    volumes:
    - /home/kaalu/volumes/arr/requesterr/config:/root/config
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true