services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eire
    volumes:
      - /home/kaalu/volumes/mylar3:/config
      - /home/kaalu/downloads/manga:/comics
      - /home/kaalu/downloads:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true