services:
  db:
    image: mariadb:latest
    # user: "1000:1000"
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /home/kaalu/volumes/nextcloud/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=MainNahiBataunga9594958505
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - homelab
    healthcheck:
      test: ["CMD", "mariadb-admin", "-u", "root", "-pMainNahiBataunga9594958505", "ping", "--silent"]


  redis:
    image: redis:alpine
    restart: always
    networks:
      - homelab

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eire
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=arnavbhattacharya.com
    volumes:
      - /home/kaalu/volumes/nextcloud/config:/config
      - ${STORAGE_LOCATION}:/data
    ports:
      - 9875:80
      - 9876:443
    networks:
      - homelab
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

networks:
  homelab:
    external: true